import type { SessionData, UserRecord } from '../types';
import { htmlEscape } from '../utils/encoding';

const shellCss = `
:root{color-scheme:dark;--bg:#080a0f;--panel:#0f131b;--panel2:#131925;--line:#232b3a;--text:#edf2ff;--muted:#8995aa;--accent:#7c5cff;--good:#38d996;--bad:#ff647c;--warn:#ffbd59}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 20% -10%,#1c1740 0,transparent 35%),var(--bg);color:var(--text);font:14px/1.5 Inter,ui-sans-serif,system-ui,-apple-system,Segoe UI,sans-serif;min-height:100vh}a{color:#b8abff;text-decoration:none}input,textarea,select,button{font:inherit}.wrap{max-width:1180px;margin:auto;padding:28px}.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:24px}.brand{display:flex;gap:12px;align-items:center}.mark{width:38px;height:38px;border-radius:12px;background:linear-gradient(135deg,#9f8cff,#5f3cff);display:grid;place-items:center;font-weight:900;box-shadow:0 10px 35px #6d4aff44}.brand h1{font-size:18px;margin:0}.muted{color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:16px}.card{grid-column:span 12;background:linear-gradient(180deg,#111722,#0d1118);border:1px solid var(--line);border-radius:18px;padding:18px;box-shadow:0 18px 60px #0005}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.stat{background:var(--panel2);border:1px solid var(--line);border-radius:14px;padding:14px}.stat b{display:block;font-size:22px;margin-top:4px}.toolbar{display:flex;gap:10px;flex-wrap:wrap;align-items:center;justify-content:space-between}.btn{border:1px solid #40366f;background:#5f45e8;color:white;border-radius:10px;padding:9px 12px;cursor:pointer}.btn.ghost{background:#161c27;border-color:var(--line);color:var(--text)}.btn.danger{background:#35151e;border-color:#67303d;color:#ff9aae}.field{display:flex;flex-direction:column;gap:6px}.field input,.field textarea{width:100%;background:#0b0f16;color:var(--text);border:1px solid var(--line);border-radius:10px;padding:10px}.formgrid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.user{display:grid;grid-template-columns:1.3fr .8fr .8fr auto;gap:14px;align-items:center;padding:13px 0;border-bottom:1px solid var(--line)}.user:last-child{border-bottom:0}.pill{display:inline-flex;padding:3px 8px;border-radius:999px;background:#1d2532;color:#c5d0e2;font-size:12px}.ok{color:var(--good)}.bad{color:var(--bad)}.mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;word-break:break-all}.hidden{display:none!important}.modal{position:fixed;inset:0;background:#000a;display:grid;place-items:center;padding:20px}.modal .card{width:min(650px,100%)}.login{max-width:440px;margin:10vh auto;padding:22px}.hero{padding:28px 0}.hero h2{font-size:34px;line-height:1.1;margin:0 0 12px}.decoy{max-width:760px;margin:12vh auto;padding:30px}.bar{height:8px;border-radius:99px;background:#1d2532;overflow:hidden}.bar>i{display:block;height:100%;background:linear-gradient(90deg,#7257ff,#45d7ff)}@media(max-width:760px){.stats{grid-template-columns:1fr 1fr}.formgrid{grid-template-columns:1fr}.user{grid-template-columns:1fr}.wrap{padding:16px}}
`;

export function decoyPage() {
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Edge Status</title><style>${shellCss}</style></head><body><div class="decoy card"><div class="brand"><div class="mark">↯</div><div><h1>Edge Status</h1><div class="muted">Connectivity endpoint</div></div></div><div class="hero"><h2>Service online</h2><p class="muted">This endpoint is active and accepting secure connections.</p></div><div class="bar"><i style="width:100%"></i></div></div></body></html>`;
}

export function installPage(claimRequired: boolean, presetClaim = '', error = '') {
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>C1 Setup</title><style>${shellCss}</style></head><body><div class="login card"><div class="brand"><div class="mark">C1</div><div><h1>C1 Proxy</h1><div class="muted">First-time ownership setup</div></div></div>${error?`<p class="bad">${htmlEscape(error)}</p>`:''}<form method="post" style="margin-top:20px;display:grid;gap:12px">${claimRequired?`<label class="field"><span>Claim token</span><input name="claim" type="password" value="${htmlEscape(presetClaim)}" autocomplete="off" required></label>`:''}<label class="field"><span>Administrator password</span><input name="password" type="password" minlength="10" autocomplete="new-password" required></label><label class="field"><span>Repeat password</span><input name="password2" type="password" minlength="10" autocomplete="new-password" required></label><button class="btn" type="submit">Claim this panel</button></form><p class="muted">Use a unique password. C1 stores a salted password verifier, not the plaintext password.</p></div></body></html>`;
}

export function loginPage(error = '') {
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>C1 Login</title><style>${shellCss}</style></head><body><div class="login card"><div class="brand"><div class="mark">C1</div><div><h1>C1 Proxy</h1><div class="muted">Control plane</div></div></div>${error?`<p class="bad">${htmlEscape(error)}</p>`:''}<form method="post" style="margin-top:20px;display:grid;gap:12px"><label class="field"><span>Password</span><input name="password" type="password" autocomplete="current-password" required></label><button class="btn" type="submit">Sign in</button></form></div></body></html>`;
}

export function dashboardPage(session: SessionData) {
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>C1 Control</title><meta name="c1-csrf" content="${session.csrf}"><style>${shellCss}</style></head><body><div class="wrap"><div class="top"><div class="brand"><div class="mark">C1</div><div><h1>C1 Control</h1><div class="muted">Edge proxy control plane</div></div></div><button class="btn ghost" id="logout">Sign out</button></div><div class="stats"><div class="stat"><span class="muted">Users</span><b id="statUsers">—</b></div><div class="stat"><span class="muted">Active</span><b id="statActive">—</b></div><div class="stat"><span class="muted">Traffic</span><b id="statTraffic">—</b></div><div class="stat"><span class="muted">Health</span><b class="ok">Online</b></div></div><div class="grid" style="margin-top:16px"><section class="card"><div class="toolbar"><div><b>Users</b><div class="muted">Private credentials and subscriptions</div></div><div><button class="btn ghost" id="backup">Backup</button> <button class="btn" id="newUser">+ New user</button></div></div><div id="users" style="margin-top:12px"></div></section><section class="card"><div class="toolbar"><div><b>Network defaults</b><div class="muted">Used when a user has no per-user clean IP.</div></div><button class="btn" id="saveSettings">Save</button></div><div class="formgrid" style="margin-top:14px"><label class="field"><span>Node prefix</span><input id="nodePrefix" placeholder="C1"></label><label class="field"><span>Global clean IPs / hostnames</span><textarea id="cleanIps" rows="4" placeholder="one per line"></textarea></label></div></section></div></div><div class="modal hidden" id="userModal"><div class="card"><div class="toolbar"><b>Create user</b><button class="btn ghost" id="closeModal">Close</button></div><form id="userForm" class="formgrid" style="margin-top:16px"><label class="field"><span>Name</span><input name="name" required></label><label class="field"><span>Username</span><input name="username" pattern="[A-Za-z0-9_-]{2,32}" required></label><label class="field"><span>Total quota (GB, 0 = unlimited)</span><input name="quota_gb" type="number" min="0" step="0.1" value="0"></label><label class="field"><span>Daily quota (GB, 0 = unlimited)</span><input name="daily_quota_gb" type="number" min="0" step="0.1" value="0"></label><label class="field"><span>Expiry</span><input name="expires_at" type="datetime-local"></label><label class="field"><span>Clean IP / hostname</span><input name="clean_ip" placeholder="optional"></label><label class="field" style="grid-column:1/-1"><span>Notes</span><textarea name="notes" rows="2"></textarea></label><button class="btn" type="submit">Create user</button></form></div></div><script>
const csrf=document.querySelector('meta[name=c1-csrf]').content;const api=async(u,o={})=>{o.headers={...(o.headers||{}),'x-c1-csrf':csrf};const r=await fetch(u,o);if(!r.ok){let x;try{x=await r.json()}catch{x={error:await r.text()}}throw new Error(x.error||'Request failed')}return r};
const fmt=b=>{b=Number(b)||0;const u=['B','KB','MB','GB','TB'];let i=0;while(b>=1024&&i<u.length-1){b/=1024;i++}return b.toFixed(i?2:0)+' '+u[i]};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function load(){const [ur,sr]=await Promise.all([api('/api/users'),api('/api/settings')]);const users=(await ur.json()).users;const st=await sr.json();document.getElementById('statUsers').textContent=users.length;document.getElementById('statActive').textContent=users.filter(x=>x.enabled&&x.status==='active').length;document.getElementById('statTraffic').textContent=fmt(users.reduce((a,x)=>a+Number(x.used_bytes||0),0));document.getElementById('nodePrefix').value=st.node_prefix||'C1';document.getElementById('cleanIps').value=st.clean_ips||'';document.getElementById('users').innerHTML=users.length?users.map(function(u){var statusClass=u.status==='active'?'ok':'bad';var quota=u.quota_bytes?(' / '+fmt(u.quota_bytes)):'';var toggleText=u.enabled?'Disable':'Enable';var nextEnabled=u.enabled?0:1;return '<div class="user"><div><b>'+esc(u.name)+'</b> <span class="pill '+statusClass+'">'+esc(u.status)+'</span><div class="muted">@'+esc(u.username)+' · '+esc(u.uuid)+'</div><div class="mono"><a href="'+esc(u.subscription_url)+'" target="_blank">'+esc(u.subscription_url)+'</a></div></div><div><span class="muted">Used</span><br><b>'+fmt(u.used_bytes)+'</b>'+quota+'</div><div><span class="muted">Clean target</span><br><span>'+esc(u.clean_ip||'global/default')+'</span></div><div><button class="btn ghost" data-copy="'+esc(u.subscription_url)+'">Copy</button> <button class="btn ghost" data-toggle="'+u.id+'" data-enable="'+nextEnabled+'">'+toggleText+'</button> <button class="btn danger" data-delete="'+u.id+'">Delete</button></div></div>'}).join(''):'<p class="muted">No users yet.</p>';document.querySelectorAll('[data-copy]').forEach(function(b){b.onclick=function(){copySub(b.getAttribute('data-copy')||'')}});document.querySelectorAll('[data-toggle]').forEach(function(b){b.onclick=function(){toggleUser(b.getAttribute('data-toggle')||'',Number(b.getAttribute('data-enable')||0))}});document.querySelectorAll('[data-delete]').forEach(function(b){b.onclick=function(){delUser(b.getAttribute('data-delete')||'')}})}
window.copySub=async x=>{await navigator.clipboard.writeText(x)};window.toggleUser=async(id,en)=>{await api('/api/users/'+id,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({enabled:en})});load()};window.delUser=async id=>{if(confirm('Delete this user?')){await api('/api/users/'+id,{method:'DELETE'});load()}};
document.getElementById('newUser').onclick=()=>document.getElementById('userModal').classList.remove('hidden');document.getElementById('closeModal').onclick=()=>document.getElementById('userModal').classList.add('hidden');document.getElementById('userForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));f.quota_bytes=Math.round(Number(f.quota_gb||0)*1073741824);f.daily_quota_bytes=Math.round(Number(f.daily_quota_gb||0)*1073741824);delete f.quota_gb;delete f.daily_quota_gb;if(f.expires_at)f.expires_at=new Date(f.expires_at).toISOString();await api('/api/users',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(f)});e.target.reset();document.getElementById('userModal').classList.add('hidden');load()};
document.getElementById('saveSettings').onclick=async()=>{await api('/api/settings',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({node_prefix:document.getElementById('nodePrefix').value,clean_ips:document.getElementById('cleanIps').value})});alert('Saved')};document.getElementById('backup').onclick=()=>location.href='/api/backup';document.getElementById('logout').onclick=async()=>{await api('/logout',{method:'POST'});location.href='/login'};load().catch(e=>alert(e.message));
</script></body></html>`;
}

export function userStatusPage(user: UserRecord, status: string) {
  const quota = user.quota_bytes ? `${formatBytes(user.used_bytes)} / ${formatBytes(user.quota_bytes)}` : `${formatBytes(user.used_bytes)} / ∞`;
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Connection status</title><style>${shellCss}</style></head><body><div class="login card"><div class="brand"><div class="mark">C1</div><div><h1>${htmlEscape(user.name)}</h1><div class="muted">Subscription status</div></div></div><div style="margin-top:18px;display:grid;gap:12px"><div><span class="muted">Status</span><br><b class="${status==='active'?'ok':'bad'}">${htmlEscape(status)}</b></div><div><span class="muted">Traffic</span><br><b>${quota}</b></div><div><span class="muted">Expiry</span><br><b>${htmlEscape(user.expires_at||'Never')}</b></div></div></div></body></html>`;
}

function formatBytes(b: number) { const u=['B','KB','MB','GB','TB']; let n=Number(b)||0,i=0; while(n>=1024&&i<u.length-1){n/=1024;i++} return `${n.toFixed(i?2:0)} ${u[i]}`; }
